% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Práctica 2: Limpieza y validación de los datos},
  pdfauthor={Hernando Hernández Mariño},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Práctica 2: Limpieza y validación de los datos}
\author{Hernando Hernández Mariño}
\date{29 de mayo, 2021}

\begin{document}
\maketitle

\hypertarget{descripciuxf3n-del-dataset.-por-quuxe9-es-importante-y-quuxe9-preguntaproblema-pretende-responder}{%
\section{1. Descripción del dataset. ¿Por qué es importante y qué
pregunta/problema pretende
responder?}\label{descripciuxf3n-del-dataset.-por-quuxe9-es-importante-y-quuxe9-preguntaproblema-pretende-responder}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Lectura de datos}
\CommentTok{\#Carpeta de trabajo}
\FunctionTok{setwd}\NormalTok{(}\StringTok{"H:/Master\_Ciencia\_datos"}\NormalTok{)}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{read.csv}\NormalTok{(}\StringTok{"H:/Master\_Ciencia\_Datos/Práctica\_2/iris.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Estructura del conjunto de datos}
\FunctionTok{str}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    150 obs. of  6 variables:
##  $ Id           : int  1 2 3 4 5 6 7 8 9 10 ...
##  $ SepalLengthCm: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
##  $ SepalWidthCm : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
##  $ PetalLengthCm: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
##  $ PetalWidthCm : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
##  $ Species      : chr  "Iris-setosa" "Iris-setosa" "Iris-setosa" "Iris-setosa" ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Las primeras 5 filas}
\FunctionTok{head}\NormalTok{(data,}\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Id SepalLengthCm SepalWidthCm PetalLengthCm PetalWidthCm     Species
## 1  1           5.1          3.5           1.4          0.2 Iris-setosa
## 2  2           4.9          3.0           1.4          0.2 Iris-setosa
## 3  3           4.7          3.2           1.3          0.2 Iris-setosa
## 4  4           4.6          3.1           1.5          0.2 Iris-setosa
## 5  5           5.0          3.6           1.4          0.2 Iris-setosa
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#Las últimas 5 filas}
\FunctionTok{tail}\NormalTok{(data ,}\DecValTok{5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Id SepalLengthCm SepalWidthCm PetalLengthCm PetalWidthCm        Species
## 146 146           6.7          3.0           5.2          2.3 Iris-virginica
## 147 147           6.3          2.5           5.0          1.9 Iris-virginica
## 148 148           6.5          3.0           5.2          2.0 Iris-virginica
## 149 149           6.2          3.4           5.4          2.3 Iris-virginica
## 150 150           5.9          3.0           5.1          1.8 Iris-virginica
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Añadir las variables del data frame al entorno global de R.}
\FunctionTok{attach}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

El conjunto de datos objeto de análisis se ha obtenido a partir del
enlace en Kaggle, el cual contiene la longitud y la anchura de los
pétalos y sépalos y la especie de 150 flores iris. De manera que es un
conjunto de datos multivariante comprendido por 5 características
(columnas) de 150 flores iris (filas o registros).

El famoso estadístico Sir Ronald. A. Fisher usó este conjunto de datos
en su artículo «The Use of Multiple Measurements in Taxonomic Problems»
(Annals of Eugenics 7 (1936), pp.~179--188). A veces se llama el
conjunto de datos Iris de Anderson porque Edgar Anderson recopiló los
datos para cuantificar la variación morfológica de las flores de Iris de
tres especies relacionadas. Dos de las tres especies fueron recogidas en
la Península de Gaspé ``todas del mismo pasto, y recogidas el mismo día
y medidas al mismo tiempo por la misma persona con el mismo aparato''.

El conjunto de datos consta de 50 muestras de cada una de las tres
especies de Iris (Iris setosa, Iris virginica e Iris versicolor). Se
midieron cuatro características de cada muestra: la longitud y la
anchura de los sépalos y pétalos, en centímetros. Basándose en la
combinación de estas cuatro características, Fisher desarrolló un modelo
discriminatorio lineal para distinguir la especie entre sí.

La idea es realizar con este conjunto de datos un análisis exploratorio
o descriptivo que permita resumir, representar y explicar los datos
concretos a disposición. Igualmente se pretenden plantear un modelo
estadístico que logre predecir o clasificar las tres especies a partir
de los 4 atributos enunciados anteriormente, lo cual se convierta en un
caso de prueba y aprendizaje para las técnicas de clasificación
estadística en el aprendizaje automático.

\hypertarget{integraciuxf3n-y-selecciuxf3n-de-los-datos-de-interuxe9s-a-analizar.}{%
\section{2. Integración y selección de los datos de interés a
analizar.}\label{integraciuxf3n-y-selecciuxf3n-de-los-datos-de-interuxe9s-a-analizar.}}

No se realizaron procesos de integración o fusión de datos tales como
añadir nuevos atributos o registros a la base original, pues no se
considera necesario, por ahora, al logro de los objetivos planteados.

En cuanto a la selección de los datos se consideran todos los atributos
a excepción del primer campo Id, dado que no es un atributo que mida
algún tipo de característica relevante que aporte al ejercicio
analítico.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# eliminar columna Id}
\NormalTok{data}\SpecialCharTok{$}\NormalTok{Id }\OtherTok{\textless{}{-}} \ConstantTok{NULL}
\end{Highlighting}
\end{Shaded}

Ahora bien al revisar el tipo de atributo o variable del dataset
importado se observa que todos los atributos son numéricos a excepción
del atributo Species, el cual se ha importado como un vector de
palabras: lo indica el chr, de character, en la fila correspondiente del
resultado de str. Esta variable Species es de tipo categórico y tiene
asociada una descripción, una cadena de caracteres y, al mismo tiempo
cuenta con un limitado número de valores posibles. Almacenar estos datos
directamente como cadenas de caracteres implica un uso de memoria
innecesario, ya que cada una de las apariciones en la base de datos
puede asociarse con un índice numérico sobre el conjunto total de
valores posibles, obteniendo una representación mucho más compacta. Para
tal fin, el atributo Species se crea como factor, de tal manera que este
-el factor- se almacena internamente como un número y las etiquetas
asociadas a cada valor se denominan niveles, que en este caso serán
tres.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Transformar Species en Factor}
\NormalTok{data }\OtherTok{\textless{}{-}} \FunctionTok{data.frame}\NormalTok{(SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm, }
\NormalTok{                   Species, }\AttributeTok{stringsAsFactors=}\ConstantTok{TRUE}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Verificación}
\FunctionTok{str}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    150 obs. of  5 variables:
##  $ SepalLengthCm: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
##  $ SepalWidthCm : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
##  $ PetalLengthCm: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
##  $ PetalWidthCm : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
##  $ Species      : Factor w/ 3 levels "Iris-setosa",..: 1 1 1 1 1 1 1 1 1 1 ...
\end{verbatim}

\hypertarget{limpieza-de-los-datos.}{%
\section{3. Limpieza de los datos.}\label{limpieza-de-los-datos.}}

\hypertarget{los-datos-contienen-ceros-o-elementos-vacuxedos-cuxf3mo-gestionaruxedas-cada-uno-de-estos-casos}{%
\subsection{3.1. ¿Los datos contienen ceros o elementos vacíos? ¿Cómo
gestionarías cada uno de estos
casos?}\label{los-datos-contienen-ceros-o-elementos-vacuxedos-cuxf3mo-gestionaruxedas-cada-uno-de-estos-casos}}

No se identifican valores perdidos o ausentes (NA) en el dataset. En la
gestión de datos ausentes se puede optar por eliminarlos o sustituirlos
por el valor promedio de la columna o el valor más frecuente e incluso
pueden ser reemplazados a partir de un modelo de regresión que predice
dicho valor vacío; el camino a seguir dependerá de los datos a
disposición y de los objetivos del análisis a realizar.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# valores ausentes}
\FunctionTok{anyNA}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] FALSE
\end{verbatim}

\hypertarget{identificaciuxf3n-y-tratamiento-de-valores-extremos.}{%
\subsection{3.2. Identificación y tratamiento de valores
extremos.}\label{identificaciuxf3n-y-tratamiento-de-valores-extremos.}}

Con el fin de identificar valores extremos se presentan diagramas de
caja por cada una de las cuatro características y según la especie de
flor. Pero antes se presentan estadísticos descriptivos de cada una de
las cuatro características y según la especie de flor con el fin de
notar diferencias entre las especies.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Estadisticos descriptivos}
\FunctionTok{summary}\NormalTok{(data)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  SepalLengthCm    SepalWidthCm   PetalLengthCm    PetalWidthCm  
##  Min.   :4.300   Min.   :2.000   Min.   :1.000   Min.   :0.100  
##  1st Qu.:5.100   1st Qu.:2.800   1st Qu.:1.600   1st Qu.:0.300  
##  Median :5.800   Median :3.000   Median :4.350   Median :1.300  
##  Mean   :5.843   Mean   :3.054   Mean   :3.759   Mean   :1.199  
##  3rd Qu.:6.400   3rd Qu.:3.300   3rd Qu.:5.100   3rd Qu.:1.800  
##  Max.   :7.900   Max.   :4.400   Max.   :6.900   Max.   :2.500  
##             Species  
##  Iris-setosa    :50  
##  Iris-versicolor:50  
##  Iris-virginica :50  
##                      
##                      
## 
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Estadisticos descriptivos por especie}
\FunctionTok{tapply}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{SepalLengthCm, data}\SpecialCharTok{$}\NormalTok{Species, summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`Iris-setosa`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   4.300   4.800   5.000   5.006   5.200   5.800 
## 
## $`Iris-versicolor`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   4.900   5.600   5.900   5.936   6.300   7.000 
## 
## $`Iris-virginica`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   4.900   6.225   6.500   6.588   6.900   7.900
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tapply}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{SepalWidthCm, data}\SpecialCharTok{$}\NormalTok{Species, summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`Iris-setosa`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   2.300   3.125   3.400   3.418   3.675   4.400 
## 
## $`Iris-versicolor`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   2.000   2.525   2.800   2.770   3.000   3.400 
## 
## $`Iris-virginica`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   2.200   2.800   3.000   2.974   3.175   3.800
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tapply}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{PetalLengthCm, data}\SpecialCharTok{$}\NormalTok{Species, summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`Iris-setosa`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.000   1.400   1.500   1.464   1.575   1.900 
## 
## $`Iris-versicolor`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    3.00    4.00    4.35    4.26    4.60    5.10 
## 
## $`Iris-virginica`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   4.500   5.100   5.550   5.552   5.875   6.900
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{tapply}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{PetalWidthCm, data}\SpecialCharTok{$}\NormalTok{Species, summary)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`Iris-setosa`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.100   0.200   0.200   0.244   0.300   0.600 
## 
## $`Iris-versicolor`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.000   1.200   1.300   1.326   1.500   1.800 
## 
## $`Iris-virginica`
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   1.400   1.800   2.000   2.026   2.300   2.500
\end{verbatim}

Los estadísticos de tendencia central de la longitud y del ancho del
sépalo entre las especies presentan diferencias marcadas; por ejemplo,
la media y mediana de la longitud del sépalo de la especie virginica es
mayor que las otras dos especies. En contraste, el ancho del sépalo -su
media y mediana- es superior en la especie setosa. En cuanto a la
longitud y ancho del sépalo, la especie virginica es mayor frente a las
otras dos especies.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Por cada varaible en un solo gráfico}
\FunctionTok{boxplot}\NormalTok{(SepalLengthCm, SepalWidthCm, PetalLengthCm, PetalWidthCm,   }
        \AttributeTok{names =}\FunctionTok{c}\NormalTok{(}\StringTok{"Longitud del sépalo"}\NormalTok{,}\StringTok{"Ancho del sépalo"}\NormalTok{,}\StringTok{"Longitud del pétalo"}\NormalTok{,}
                \StringTok{"Ancho del pétalo"}\NormalTok{), }\AttributeTok{horizontal=}\ConstantTok{FALSE}\NormalTok{,}\AttributeTok{main=}\StringTok{"Diagramas de caja Iris"}\NormalTok{,}
        \AttributeTok{col =} \FunctionTok{c}\NormalTok{(}\StringTok{"orange3"}\NormalTok{, }\StringTok{"yellow3"}\NormalTok{, }\StringTok{"green3"}\NormalTok{, }\StringTok{"grey"}\NormalTok{),}
        \AttributeTok{xlab =} \StringTok{"Atributos"}\NormalTok{, }\AttributeTok{ylab =} \StringTok{"Centimetros"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck8-1.pdf}

En los diagramas de caja de los cuatro atributos se observan diferencias
marcadas en su mediana tanto en las longitudes como en los anchos del
sépalo y pétalo de las flores iris. También se identifican algunos
valores extremos en el atributo Ancho del sépalo.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Por cada variable según su especie}

\NormalTok{BpSl }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(iris, }\FunctionTok{aes}\NormalTok{(Species, SepalLengthCm, }\AttributeTok{fill=}\NormalTok{Species)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_boxplot}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\StringTok{"Longitud del sépalo (cm)"}\NormalTok{, }\AttributeTok{breaks=} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{30}\NormalTok{, }\AttributeTok{by=}\NormalTok{.}\DecValTok{5}\NormalTok{))}\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position=}\StringTok{"none"}\NormalTok{)}

\NormalTok{BpSw }\OtherTok{\textless{}{-}}  \FunctionTok{ggplot}\NormalTok{(iris, }\FunctionTok{aes}\NormalTok{(Species, SepalWidthCm, }\AttributeTok{fill=}\NormalTok{Species)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_boxplot}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\StringTok{"Ancho del sépalo (cm)"}\NormalTok{, }\AttributeTok{breaks=} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{30}\NormalTok{, }\AttributeTok{by=}\NormalTok{.}\DecValTok{5}\NormalTok{))}\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position=}\StringTok{"none"}\NormalTok{)}

\NormalTok{BpPl }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(iris, }\FunctionTok{aes}\NormalTok{(Species, PetalLengthCm, }\AttributeTok{fill=}\NormalTok{Species)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_boxplot}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\StringTok{"Longitud del pétalo (cm)"}\NormalTok{, }\AttributeTok{breaks=} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{30}\NormalTok{, }\AttributeTok{by=}\NormalTok{.}\DecValTok{5}\NormalTok{))}\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position=}\StringTok{"none"}\NormalTok{)}

\NormalTok{BpPw }\OtherTok{\textless{}{-}}  \FunctionTok{ggplot}\NormalTok{(iris, }\FunctionTok{aes}\NormalTok{(Species, PetalWidthCm, }\AttributeTok{fill=}\NormalTok{Species)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_boxplot}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{scale\_y\_continuous}\NormalTok{(}\StringTok{"Ancho del pétalo (cm)"}\NormalTok{, }\AttributeTok{breaks=} \FunctionTok{seq}\NormalTok{(}\DecValTok{0}\NormalTok{,}\DecValTok{30}\NormalTok{, }\AttributeTok{by=}\NormalTok{.}\DecValTok{5}\NormalTok{))}\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{title =} \StringTok{"Iris Box Plot"}\NormalTok{, }\AttributeTok{x =} \StringTok{"Species"}\NormalTok{)}

\FunctionTok{grid.arrange}\NormalTok{(BpSl  }\SpecialCharTok{+} \FunctionTok{ggtitle}\NormalTok{(}\StringTok{""}\NormalTok{),}
\NormalTok{             BpSw  }\SpecialCharTok{+} \FunctionTok{ggtitle}\NormalTok{(}\StringTok{""}\NormalTok{),}
\NormalTok{             BpPl }\SpecialCharTok{+} \FunctionTok{ggtitle}\NormalTok{(}\StringTok{""}\NormalTok{),}
\NormalTok{             BpPw }\SpecialCharTok{+} \FunctionTok{ggtitle}\NormalTok{(}\StringTok{""}\NormalTok{),}
             \AttributeTok{nrow =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck9-1.pdf}

Igualmente al realizar los diagramas de caja de los atributos de acuerdo
con cada especie de iris se observan diferencias relevantes en las
medianas de la longitud y ancho del pétalo, así como la longitud del
sépalo; pero en el ancho del sépalo, si bien se presentan diferencias en
sus medianas estas son menos marcadas. Por otra parte, también se
identifican valores extremos en las características de longitud y ancho
del pétalo de la especie setosa y de la especie virginica en las
características de longitud y ancho del sépalo. Por ahora, se mantendrán
todos los valores extremos identificados en el ejercicio analítico de
este dataset.

Una vez realizado sobre el conjunto de datos inicial los procedimientos
de integración, validación y limpieza anteriores, procedemos a guardar
estos en un nuevo fichero denominado Automobile\_data\_clean.csv:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Exportación de los datos preprocesados}
\FunctionTok{write.csv}\NormalTok{(data, }\StringTok{"data\_clean.csv"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{anuxe1lisis-de-los-datos.}{%
\section{4. Análisis de los datos.}\label{anuxe1lisis-de-los-datos.}}

\hypertarget{selecciuxf3n-de-los-grupos-de-datos-que-se-quieren-analizarcomparar-planificaciuxf3n-de-los-anuxe1lisis-a-aplicar.}{%
\subsection{4.1. Selección de los grupos de datos que se quieren
analizar/comparar (planificación de los análisis a
aplicar).}\label{selecciuxf3n-de-los-grupos-de-datos-que-se-quieren-analizarcomparar-planificaciuxf3n-de-los-anuxe1lisis-a-aplicar.}}

Se divide el dataset iris en varios datasets, los cuales contienen cada
uno las muestras pertenecientes a una especie de flor que sería
interesante analizar y/o comparar; sin embargo, no todos se utilizarían
en la realización de pruebas estadísticas posteriores.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Separar en grupos según un factor}
\NormalTok{setosa }\OtherTok{\textless{}{-}}\NormalTok{ data[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{50}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{]}
\NormalTok{versicolor }\OtherTok{\textless{}{-}}\NormalTok{ data[}\DecValTok{51}\SpecialCharTok{:}\DecValTok{100}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{]}
\NormalTok{virginica }\OtherTok{\textless{}{-}}\NormalTok{ data[}\DecValTok{101}\SpecialCharTok{:}\DecValTok{150}\NormalTok{, }\DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{]}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# verificación}
\FunctionTok{str}\NormalTok{(setosa)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    50 obs. of  4 variables:
##  $ SepalLengthCm: num  5.1 4.9 4.7 4.6 5 5.4 4.6 5 4.4 4.9 ...
##  $ SepalWidthCm : num  3.5 3 3.2 3.1 3.6 3.9 3.4 3.4 2.9 3.1 ...
##  $ PetalLengthCm: num  1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5 ...
##  $ PetalWidthCm : num  0.2 0.2 0.2 0.2 0.2 0.4 0.3 0.2 0.2 0.1 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(versicolor)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    50 obs. of  4 variables:
##  $ SepalLengthCm: num  7 6.4 6.9 5.5 6.5 5.7 6.3 4.9 6.6 5.2 ...
##  $ SepalWidthCm : num  3.2 3.2 3.1 2.3 2.8 2.8 3.3 2.4 2.9 2.7 ...
##  $ PetalLengthCm: num  4.7 4.5 4.9 4 4.6 4.5 4.7 3.3 4.6 3.9 ...
##  $ PetalWidthCm : num  1.4 1.5 1.5 1.3 1.5 1.3 1.6 1 1.3 1.4 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(virginica)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    50 obs. of  4 variables:
##  $ SepalLengthCm: num  6.3 5.8 7.1 6.3 6.5 7.6 4.9 7.3 6.7 7.2 ...
##  $ SepalWidthCm : num  3.3 2.7 3 2.9 3 3 2.5 2.9 2.5 3.6 ...
##  $ PetalLengthCm: num  6 5.1 5.9 5.6 5.8 6.6 4.5 6.3 5.8 6.1 ...
##  $ PetalWidthCm : num  2.5 1.9 2.1 1.8 2.2 2.1 1.7 1.8 1.8 2.5 ...
\end{verbatim}

\hypertarget{comprobaciuxf3n-de-la-normalidad-y-homogeneidad-de-la-varianza.}{%
\section{4.2. Comprobación de la normalidad y homogeneidad de la
varianza.}\label{comprobaciuxf3n-de-la-normalidad-y-homogeneidad-de-la-varianza.}}

Con el fin de comprobar la normalidad de cada uno de los atributos y
según su especie de flor se presenta el histograma y curva de densidad,
gráfico de cuantiles teóricos (Q-Q plot), así como los test de
normalidad Anderson-Darling cuyo nivel de significación se fija en 0.05.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Histograma y curva de densidad}
\CommentTok{\# Longitud del sépalo}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ SepalLengthCm)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ ..density..), }\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"gray60"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{color =} \StringTok{"Longitud de sépalo"}\NormalTok{), }\AttributeTok{lwd =} \FloatTok{0.95}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{stat\_function}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{color =} \StringTok{"Normal"}\NormalTok{), }\AttributeTok{fun =}\NormalTok{ dnorm, }\AttributeTok{lwd =} \FloatTok{0.95}\NormalTok{,}
                \AttributeTok{args =} \FunctionTok{list}\NormalTok{(}\AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{SepalLengthCm),}
                            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{SepalLengthCm))) }\SpecialCharTok{+}
  \FunctionTok{scale\_colour\_manual}\NormalTok{(}\StringTok{"Densidad"}\NormalTok{, }\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"red"}\NormalTok{, }\StringTok{"blue"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Longitud de sépalo (cm)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Densidad"}\NormalTok{,}
       \AttributeTok{title =} \StringTok{"Distribución de la longitud de sépalo vs curva normal"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{Práctica_2_files/figure-latex/chunck13-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Longitud del sépalo}
\CommentTok{\# gráfico de cuantiles teóricos (Q{-}Q plot)}
\FunctionTok{qqnorm}\NormalTok{(}\AttributeTok{y =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{SepalLengthCm)}
\FunctionTok{qqline}\NormalTok{(}\AttributeTok{y =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{SepalLengthCm)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck14-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Longitud del sépalo}
\CommentTok{\# Prueba de normalidad}
\CommentTok{\# Anderson{-}Darling}
\FunctionTok{ad.test}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{SepalLengthCm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Anderson-Darling normality test
## 
## data:  data$SepalLengthCm
## A = 0.8892, p-value = 0.02251
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Histograma y curva de densidad}
\CommentTok{\# Ancho del sépalo}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ SepalWidthCm)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ ..density..), }\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"gray60"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{color =} \StringTok{"Ancho del sépalo"}\NormalTok{), }\AttributeTok{lwd =} \FloatTok{0.95}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{stat\_function}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{color =} \StringTok{"Normal"}\NormalTok{), }\AttributeTok{fun =}\NormalTok{ dnorm, }\AttributeTok{lwd =} \FloatTok{0.95}\NormalTok{,}
                \AttributeTok{args =} \FunctionTok{list}\NormalTok{(}\AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{SepalWidthCm),}
                            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{SepalWidthCm))) }\SpecialCharTok{+}
  \FunctionTok{scale\_colour\_manual}\NormalTok{(}\StringTok{"Densidad"}\NormalTok{, }\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"red"}\NormalTok{, }\StringTok{"blue"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Ancho del sépalo (cm)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Densidad"}\NormalTok{,}
       \AttributeTok{title =} \StringTok{"Distribución del ancho del sépalo vs curva normal"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{Práctica_2_files/figure-latex/chunck16-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Ancho del sépalo}
\CommentTok{\# gráfico de cuantiles teóricos (Q{-}Q plot)}
\FunctionTok{qqnorm}\NormalTok{(}\AttributeTok{y =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{SepalWidthCm)}
\FunctionTok{qqline}\NormalTok{(}\AttributeTok{y =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{SepalWidthCm)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck17-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Ancho del sépalo}
\CommentTok{\# Prueba de normalidad}
\CommentTok{\# Anderson{-}Darling}
\FunctionTok{ad.test}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{SepalWidthCm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Anderson-Darling normality test
## 
## data:  data$SepalWidthCm
## A = 0.96566, p-value = 0.01455
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Longitud del pétalo }
\CommentTok{\# Histograma y curva de densidad}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ PetalLengthCm)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ ..density..), }\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"gray60"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{color =} \StringTok{"Longitud del pétalo"}\NormalTok{), }\AttributeTok{lwd =} \FloatTok{0.95}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{stat\_function}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{color =} \StringTok{"Normal"}\NormalTok{), }\AttributeTok{fun =}\NormalTok{ dnorm, }\AttributeTok{lwd =} \FloatTok{0.95}\NormalTok{,}
                \AttributeTok{args =} \FunctionTok{list}\NormalTok{(}\AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{PetalLengthCm),}
                            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{PetalLengthCm))) }\SpecialCharTok{+}
  \FunctionTok{scale\_colour\_manual}\NormalTok{(}\StringTok{"Densidad"}\NormalTok{, }\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"red"}\NormalTok{, }\StringTok{"blue"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Longitud del pétalo (cm)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Densidad"}\NormalTok{,}
       \AttributeTok{title =} \StringTok{"Distribución de la longitud del pétalo vs curva normal"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{Práctica_2_files/figure-latex/chunck19-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Longitud del pétalo}
\CommentTok{\# gráfico de cuantiles teóricos (Q{-}Q plot)}
\FunctionTok{qqnorm}\NormalTok{(}\AttributeTok{y =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{PetalLengthCm)}
\FunctionTok{qqline}\NormalTok{(}\AttributeTok{y =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{PetalWidthCm)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck20-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Longitud del pétalo}
\CommentTok{\# Prueba de normalidad}
\CommentTok{\# Anderson{-}Darling}
\FunctionTok{ad.test}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{PetalLengthCm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Anderson-Darling normality test
## 
## data:  data$PetalLengthCm
## A = 7.6729, p-value < 2.2e-16
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Ancho del pétalo }
\CommentTok{\# Histograma y curva de densidad}
\FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data =}\NormalTok{ data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ PetalWidthCm)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{y =}\NormalTok{ ..density..), }\AttributeTok{color =} \StringTok{"black"}\NormalTok{, }\AttributeTok{fill =} \StringTok{"gray60"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{color =} \StringTok{"Ancho del pétalo"}\NormalTok{), }\AttributeTok{lwd =} \FloatTok{0.95}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{stat\_function}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{color =} \StringTok{"Normal"}\NormalTok{), }\AttributeTok{fun =}\NormalTok{ dnorm, }\AttributeTok{lwd =} \FloatTok{0.95}\NormalTok{,}
                \AttributeTok{args =} \FunctionTok{list}\NormalTok{(}\AttributeTok{mean =} \FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{PetalWidthCm),}
                            \AttributeTok{sd =} \FunctionTok{sd}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{PetalWidthCm))) }\SpecialCharTok{+}
  \FunctionTok{scale\_colour\_manual}\NormalTok{(}\StringTok{"Densidad"}\NormalTok{, }\AttributeTok{values =} \FunctionTok{c}\NormalTok{(}\StringTok{"red"}\NormalTok{, }\StringTok{"blue"}\NormalTok{)) }\SpecialCharTok{+}
  \FunctionTok{labs}\NormalTok{(}\AttributeTok{x =} \StringTok{"Ancho del pétalo (cm)"}\NormalTok{, }\AttributeTok{y =} \StringTok{"Densidad"}\NormalTok{,}
       \AttributeTok{title =} \StringTok{"Distribución del ancho del pétalo vs curva normal"}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{theme\_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `stat_bin()` using `bins = 30`. Pick better value with `binwidth`.
\end{verbatim}

\includegraphics{Práctica_2_files/figure-latex/chunck22-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Ancho del pétalo}
\CommentTok{\# gráfico de cuantiles teóricos (Q{-}Q plot)}
\FunctionTok{qqnorm}\NormalTok{(}\AttributeTok{y =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{PetalWidthCm)}
\FunctionTok{qqline}\NormalTok{(}\AttributeTok{y =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{PetalWidthCm)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck23-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Ancho del pétalo}
\CommentTok{\# Prueba de normalidad}
\CommentTok{\# Anderson{-}Darling}
\FunctionTok{ad.test}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{PetalWidthCm)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Anderson-Darling normality test
## 
## data:  data$PetalWidthCm
## A = 5.0628, p-value = 1.427e-12
\end{verbatim}

En el caso de los atributos longitud y ancho del sépalo, los gráficos
indican que su distribución se aleja de la distribución normal, lo cual
se verifica en el test aplicado, pues el valor P (0.02251 y 0.01455
respectivamente) es menor que el nivel de significancia (0.05), por
tanto, existe evidencia para rechazar hipótesis nula, es decir, que los
datos no provienen de una población con distribución normal.

En el caso de los atributos longitud y ancho del pétalo, los gráficos
indican que su distribución se aleja de la distribución normal, lo cual
se verifica en el test aplicado, pues el valor P (2.2e-16 y 1.427e-12
respectivamente) es menor que el nivel de significancia (0.05), por
tanto, existe evidencia para rechazar hipótesis nula, es decir, que los
datos no provienen de una población con distribución normal.

Estos resultados -en particular la distribución de los atributos-
también sugieren la presencia de diferentes muestras, es decir, se
evidencia la influencia de las tres especies de flores.

Ahora bien, al analizar los atributos de longitud y ancho del sépalo y
pétalo según cada una de las tres especies, a partir del histograma y
curva de densidad, así como el grafico Q-Q y el test de normalidad
Anderson-Darling se observa lo siguiente:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# tipo de flor setosa}
\CommentTok{\# Histograma y curva de densidad}
\NormalTok{result}\OtherTok{\textless{}{-}} \FunctionTok{mvn}\NormalTok{(}\AttributeTok{data=}\NormalTok{setosa, }\AttributeTok{mvnTest=}\StringTok{"royston"}\NormalTok{, }\AttributeTok{univariatePlot=}\StringTok{"histogram"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck25-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# tipo de flor setosa}
\CommentTok{\# Gráfico Q{-}Q}
\NormalTok{result}\OtherTok{\textless{}{-}}\FunctionTok{mvn}\NormalTok{(}\AttributeTok{data=}\NormalTok{setosa, }\AttributeTok{mvnTest =} \StringTok{"royston"}\NormalTok{, }\AttributeTok{univariatePlot =} \StringTok{"qqplot"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck26-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# tipo de flor setosa}
\CommentTok{\# Test de Anderson Darling}
\NormalTok{result }\OtherTok{\textless{}{-}} \FunctionTok{mvn}\NormalTok{(}\AttributeTok{data =}\NormalTok{ setosa, }\AttributeTok{mvnTest =} \StringTok{"royston"}\NormalTok{, }\AttributeTok{univariateTest =} \StringTok{"AD"}\NormalTok{, }\AttributeTok{desc =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{result}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $multivariateNormality
##      Test        H      p value MVN
## 1 Royston 30.37255 3.721164e-06  NO
## 
## $univariateNormality
##               Test      Variable Statistic   p value Normality
## 1 Anderson-Darling SepalLengthCm    0.4080  0.3352      YES   
## 2 Anderson-Darling SepalWidthCm     0.5635  0.1375      YES   
## 3 Anderson-Darling PetalLengthCm    1.0111  0.0106      NO    
## 4 Anderson-Darling PetalWidthCm     4.3070  <0.001      NO    
## 
## $Descriptives
##                n  Mean   Std.Dev Median Min Max  25th  75th       Skew
## SepalLengthCm 50 5.006 0.3524897    5.0 4.3 5.8 4.800 5.200 0.11297784
## SepalWidthCm  50 3.418 0.3810244    3.4 2.3 4.4 3.125 3.675 0.10071528
## PetalLengthCm 50 1.464 0.1735112    1.5 1.0 1.9 1.400 1.575 0.06759284
## PetalWidthCm  50 0.244 0.1072095    0.2 0.1 0.6 0.200 0.300 1.12636619
##                 Kurtosis
## SepalLengthCm -0.4508724
## SepalWidthCm   0.5392028
## PetalLengthCm  0.6626438
## PetalWidthCm   1.1263351
\end{verbatim}

En el caso de la especie setosa el ancho del pétalo tiene una
distribución sesgada a la derecha mientras que las otras variables
tienen distribuciones aproximadamente normales. De acuerdo con el
gráfico Q-Q se presentan algunas desviaciones de la línea recta y esto
indica posibles desviaciones de una distribución normal, particularmente
en el ancho del pétalo. Y según el test de normalidad, las variables
longitud y ancho del pétalo no provienen de poblaciones normales, lo
cual confirma lo señalado en los gráficos descritos anteriormente.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# tipo de flor versicolor}
\CommentTok{\# Histograma y curva de densidad}
\NormalTok{result}\OtherTok{\textless{}{-}} \FunctionTok{mvn}\NormalTok{(}\AttributeTok{data=}\NormalTok{versicolor, }\AttributeTok{mvnTest=}\StringTok{"royston"}\NormalTok{, }\AttributeTok{univariatePlot=}\StringTok{"histogram"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck28-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# tipo de flor versicolor}
\CommentTok{\# Gráfico Q{-}Q}
\NormalTok{result}\OtherTok{\textless{}{-}}\FunctionTok{mvn}\NormalTok{(}\AttributeTok{data=}\NormalTok{versicolor, }\AttributeTok{mvnTest =} \StringTok{"royston"}\NormalTok{, }\AttributeTok{univariatePlot =} \StringTok{"qqplot"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck29-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# tipo de flor versicolor}
\CommentTok{\# Test de Anderson Darling}
\NormalTok{result }\OtherTok{\textless{}{-}} \FunctionTok{mvn}\NormalTok{(}\AttributeTok{data =}\NormalTok{ versicolor, }\AttributeTok{mvnTest =} \StringTok{"royston"}\NormalTok{, }\AttributeTok{univariateTest =} \StringTok{"AD"}\NormalTok{, }\AttributeTok{desc =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{result}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $multivariateNormality
##      Test       H   p value MVN
## 1 Royston 7.85262 0.0847746 YES
## 
## $univariateNormality
##               Test      Variable Statistic   p value Normality
## 1 Anderson-Darling SepalLengthCm    0.3608    0.4333    YES   
## 2 Anderson-Darling SepalWidthCm     0.5598    0.1406    YES   
## 3 Anderson-Darling PetalLengthCm    0.5551    0.1446    YES   
## 4 Anderson-Darling PetalWidthCm     0.9569    0.0144    NO    
## 
## $Descriptives
##                n  Mean   Std.Dev Median Min Max  25th 75th        Skew
## SepalLengthCm 50 5.936 0.5161711   5.90 4.9 7.0 5.600  6.3  0.09913926
## SepalWidthCm  50 2.770 0.3137983   2.80 2.0 3.4 2.525  3.0 -0.34136443
## PetalLengthCm 50 4.260 0.4699110   4.35 3.0 5.1 4.000  4.6 -0.57060243
## PetalWidthCm  50 1.326 0.1977527   1.30 1.0 1.8 1.200  1.5 -0.02933377
##                 Kurtosis
## SepalLengthCm -0.6939138
## SepalWidthCm  -0.5493203
## PetalLengthCm -0.1902555
## PetalWidthCm  -0.5873144
\end{verbatim}

En cuanto a la especie versicolor el ancho del pétalo tiene una
distribución sesgada a la derecha mientras que las otras variables
tienen distribuciones aproximadamente normales. De acuerdo con el
gráfico Q-Q se presentan algunas desviaciones de la línea recta y esto
indica posibles desviaciones de una distribución normal, particularmente
en el ancho del pétalo. Y según el test de normalidad, la variable ancho
del pétalo no proviene de poblaciones normales, lo cual confirma lo
señalado en los gráficos descritos anteriormente.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# tipo de flor virginica}
\CommentTok{\# Histograma y curva de densidad}
\NormalTok{result}\OtherTok{\textless{}{-}} \FunctionTok{mvn}\NormalTok{(}\AttributeTok{data=}\NormalTok{virginica, }\AttributeTok{mvnTest=}\StringTok{"royston"}\NormalTok{, }\AttributeTok{univariatePlot=}\StringTok{"histogram"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck31-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# tipo de flor virginica}
\CommentTok{\# Gráfico Q{-}Q}
\NormalTok{result}\OtherTok{\textless{}{-}}\FunctionTok{mvn}\NormalTok{(}\AttributeTok{data=}\NormalTok{virginica, }\AttributeTok{mvnTest =} \StringTok{"royston"}\NormalTok{, }\AttributeTok{univariatePlot =} \StringTok{"qqplot"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck32-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# tipo de flor virginica}
\CommentTok{\# Test de Anderson Darling}
\NormalTok{result }\OtherTok{\textless{}{-}} \FunctionTok{mvn}\NormalTok{(}\AttributeTok{data =}\NormalTok{ virginica, }\AttributeTok{mvnTest =} \StringTok{"royston"}\NormalTok{, }\AttributeTok{univariateTest =} \StringTok{"AD"}\NormalTok{, }\AttributeTok{desc =} \ConstantTok{TRUE}\NormalTok{)}
\NormalTok{result}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $multivariateNormality
##      Test        H    p value MVN
## 1 Royston 8.141444 0.06776605 YES
## 
## $univariateNormality
##               Test      Variable Statistic   p value Normality
## 1 Anderson-Darling SepalLengthCm    0.5516    0.1475    YES   
## 2 Anderson-Darling SepalWidthCm     0.6182    0.1018    YES   
## 3 Anderson-Darling PetalLengthCm    0.6090    0.1074    YES   
## 4 Anderson-Darling PetalWidthCm     0.7388    0.0508    YES   
## 
## $Descriptives
##                n  Mean   Std.Dev Median Min Max  25th  75th       Skew
## SepalLengthCm 50 6.588 0.6358796   6.50 4.9 7.9 6.225 6.900  0.1110286
## SepalWidthCm  50 2.974 0.3224966   3.00 2.2 3.8 2.800 3.175  0.3442849
## PetalLengthCm 50 5.552 0.5518947   5.55 4.5 6.9 5.100 5.875  0.5169175
## PetalWidthCm  50 2.026 0.2746501   2.00 1.4 2.5 1.800 2.300 -0.1218119
##                 Kurtosis
## SepalLengthCm -0.2032597
## SepalWidthCm   0.3803832
## PetalLengthCm -0.3651161
## PetalWidthCm  -0.7539586
\end{verbatim}

Y finalmente, en la especie virginica, todas las variables tienen
distribuciones aproximadamente normales. Si bien se presentan ciertas
desviaciones de la línea recta en el grafico Q-Q no son pronunciadas en
las variables en estudio. Y el test de normalidad indica que sin
excepción todas las variables provienes de poblaciones normales.

Las gráficas de histograma de frecuencias, curvas de densidad y
dispersión -según las especies de flor iris- visualizadas en conjunto
permiten identificar la posible separación de las especies y la
superposición de valores de cada especie para un atributo en específico.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Análisis de frecuencia con el histograma}
\CommentTok{\# Longitud del sépalo }
\NormalTok{HisSl }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{SepalLengthCm))}\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{binwidth=}\FloatTok{0.2}\NormalTok{, }\AttributeTok{color=}\StringTok{"black"}\NormalTok{, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill=}\NormalTok{Species)) }\SpecialCharTok{+} 
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Longitud del sépalo (cm)"}\NormalTok{) }\SpecialCharTok{+}  
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Frequencia"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position=}\StringTok{"none"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Histograma de la longitud del sépalo"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{data=}\NormalTok{data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{xintercept =} \FunctionTok{mean}\NormalTok{(SepalLengthCm)),}\AttributeTok{linetype=}\StringTok{"dashed"}\NormalTok{,}\AttributeTok{color=}\StringTok{"grey"}\NormalTok{)}
\CommentTok{\# Ancho del sépalo}
\NormalTok{HistSw }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{SepalWidthCm)) }\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{binwidth=}\FloatTok{0.2}\NormalTok{, }\AttributeTok{color=}\StringTok{"black"}\NormalTok{, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill=}\NormalTok{Species)) }\SpecialCharTok{+} 
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Ancho del sépalo (cm)"}\NormalTok{) }\SpecialCharTok{+}  
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Frequencia"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position=}\StringTok{"none"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Histograma del ancho del sépalo"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{data=}\NormalTok{data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{xintercept =} \FunctionTok{mean}\NormalTok{(SepalWidthCm)),}\AttributeTok{linetype=}\StringTok{"dashed"}\NormalTok{,}\AttributeTok{color=}\StringTok{"grey"}\NormalTok{)}
\CommentTok{\# Longitud del pétalo}
\NormalTok{HistPl }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{PetalLengthCm))}\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{binwidth=}\FloatTok{0.2}\NormalTok{, }\AttributeTok{color=}\StringTok{"black"}\NormalTok{, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill=}\NormalTok{Species)) }\SpecialCharTok{+} 
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Longitud del pétalo (cm)"}\NormalTok{) }\SpecialCharTok{+}  
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Frequencia"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position=}\StringTok{"none"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Histograma de la longitud del pétalo"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{data=}\NormalTok{data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{xintercept =} \FunctionTok{mean}\NormalTok{(PetalLengthCm)),}
             \AttributeTok{linetype=}\StringTok{"dashed"}\NormalTok{,}\AttributeTok{color=}\StringTok{"grey"}\NormalTok{)}
\CommentTok{\# Ancho del pétalo}
\NormalTok{HistPw }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(}\AttributeTok{data=}\NormalTok{data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{PetalWidthCm))}\SpecialCharTok{+}
  \FunctionTok{geom\_histogram}\NormalTok{(}\AttributeTok{binwidth=}\FloatTok{0.2}\NormalTok{, }\AttributeTok{color=}\StringTok{"black"}\NormalTok{, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{fill=}\NormalTok{Species)) }\SpecialCharTok{+} 
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Ancho del pétalo (cm)"}\NormalTok{) }\SpecialCharTok{+}  
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Frequency"}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position=}\StringTok{"right"}\NormalTok{ )}\SpecialCharTok{+}
  \FunctionTok{ggtitle}\NormalTok{(}\StringTok{"Histograma del ancho del pétalo"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\AttributeTok{data=}\NormalTok{data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{xintercept =} \FunctionTok{mean}\NormalTok{(PetalWidthCm)),}\AttributeTok{linetype=}\StringTok{"dashed"}\NormalTok{,}\AttributeTok{color=}\StringTok{"grey"}\NormalTok{)}
\CommentTok{\# Visualización en conjunto}
\FunctionTok{grid.arrange}\NormalTok{(HisSl }\SpecialCharTok{+} \FunctionTok{ggtitle}\NormalTok{(}\StringTok{""}\NormalTok{),}
\NormalTok{             HistSw }\SpecialCharTok{+} \FunctionTok{ggtitle}\NormalTok{(}\StringTok{""}\NormalTok{),}
\NormalTok{             HistPl }\SpecialCharTok{+} \FunctionTok{ggtitle}\NormalTok{(}\StringTok{""}\NormalTok{),}
\NormalTok{             HistPw  }\SpecialCharTok{+} \FunctionTok{ggtitle}\NormalTok{(}\StringTok{""}\NormalTok{),}
             \AttributeTok{nrow =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck34-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Análisis de densidad}
\CommentTok{\# Longitud del pétalo}
\NormalTok{DhistPl }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{PetalLengthCm, }\AttributeTok{colour=}\NormalTok{Species, }\AttributeTok{fill=}\NormalTok{Species)) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{alpha=}\NormalTok{.}\DecValTok{3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{xintercept=}\FunctionTok{mean}\NormalTok{(PetalLengthCm),  }\AttributeTok{colour=}\NormalTok{Species),}\AttributeTok{linetype=}\StringTok{"dashed"}\NormalTok{,}\AttributeTok{color=}\StringTok{"grey"}\NormalTok{, }\AttributeTok{size=}\DecValTok{1}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Longitud del pétalo (cm)"}\NormalTok{) }\SpecialCharTok{+}  
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Densidad"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position=}\StringTok{"none"}\NormalTok{)}
\CommentTok{\# Ancho del pétalo}
\NormalTok{DhistPw }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{PetalWidthCm, }\AttributeTok{colour=}\NormalTok{Species, }\AttributeTok{fill=}\NormalTok{Species)) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{alpha=}\NormalTok{.}\DecValTok{3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{xintercept=}\FunctionTok{mean}\NormalTok{(PetalWidthCm),  }\AttributeTok{colour=}\NormalTok{Species),}\AttributeTok{linetype=}\StringTok{"dashed"}\NormalTok{,}\AttributeTok{color=}\StringTok{"grey"}\NormalTok{, }\AttributeTok{size=}\DecValTok{1}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Ancho del pétalo (cm)"}\NormalTok{) }\SpecialCharTok{+}  
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Densidad"}\NormalTok{)}
\CommentTok{\# Ancho del sépalo}
\NormalTok{DhistSw }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{SepalWidthCm, }\AttributeTok{colour=}\NormalTok{Species, }\AttributeTok{fill=}\NormalTok{Species)) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{alpha=}\NormalTok{.}\DecValTok{3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{xintercept=}\FunctionTok{mean}\NormalTok{(SepalWidthCm),  }\AttributeTok{colour=}\NormalTok{Species), }\AttributeTok{linetype=}\StringTok{"dashed"}\NormalTok{,}\AttributeTok{color=}\StringTok{"grey"}\NormalTok{, }\AttributeTok{size=}\DecValTok{1}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Ancho del sépalo (cm)"}\NormalTok{) }\SpecialCharTok{+}  
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Densidad"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position=}\StringTok{"none"}\NormalTok{)}
\CommentTok{\# Longitud del sé©palo}
\NormalTok{DhistSl }\OtherTok{\textless{}{-}} \FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{SepalLengthCm, }\AttributeTok{colour=}\NormalTok{Species, }\AttributeTok{fill=}\NormalTok{Species)) }\SpecialCharTok{+}
  \FunctionTok{geom\_density}\NormalTok{(}\AttributeTok{alpha=}\NormalTok{.}\DecValTok{3}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_vline}\NormalTok{(}\FunctionTok{aes}\NormalTok{(}\AttributeTok{xintercept=}\FunctionTok{mean}\NormalTok{(SepalLengthCm),  }\AttributeTok{colour=}\NormalTok{Species),}\AttributeTok{linetype=}\StringTok{"dashed"}\NormalTok{, }\AttributeTok{color=}\StringTok{"grey"}\NormalTok{, }\AttributeTok{size=}\DecValTok{1}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{xlab}\NormalTok{(}\StringTok{"Longitud del sépalo (cm)"}\NormalTok{) }\SpecialCharTok{+}  
  \FunctionTok{ylab}\NormalTok{(}\StringTok{"Densidad"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme}\NormalTok{(}\AttributeTok{legend.position=}\StringTok{"none"}\NormalTok{)}
\CommentTok{\# visualización conjunta}

\FunctionTok{grid.arrange}\NormalTok{(DhistSl }\SpecialCharTok{+} \FunctionTok{ggtitle}\NormalTok{(}\StringTok{""}\NormalTok{),}
\NormalTok{             DhistSw  }\SpecialCharTok{+} \FunctionTok{ggtitle}\NormalTok{(}\StringTok{""}\NormalTok{),}
\NormalTok{             DhistPl }\SpecialCharTok{+} \FunctionTok{ggtitle}\NormalTok{(}\StringTok{""}\NormalTok{),}
\NormalTok{             DhistPw  }\SpecialCharTok{+} \FunctionTok{ggtitle}\NormalTok{(}\StringTok{""}\NormalTok{),}
             \AttributeTok{nrow =} \DecValTok{2}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck35-1.pdf}

Con relación a la homogeneidad de la varianza (la varianza es constante
(no varía) en los diferentes niveles de un factor) se utiliza el test de
Levene. Este test de Levene se caracteriza, porque en primer lugar se
puede comparar 2 o más poblaciones (en este caso son tres muestras) y,
en segundo lugar permite elegir entre diferentes estadísticos de
centralidad: mediana (por defecto), media, media truncada, lo cual es
importante a la hora de contrastar la homocedasticidad, dependiendo de
si los grupos se distribuyen de forma normal o no, lo cual como se anotó
anteriormente algunas variables no siguen una distribución normal.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Homogeneidad}
\CommentTok{\# Test de Levene}
\FunctionTok{leveneTest}\NormalTok{(}\AttributeTok{y =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{SepalLengthCm, }\AttributeTok{group =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{Species, }\AttributeTok{center =} \StringTok{"median"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Levene's Test for Homogeneity of Variance (center = "median")
##        Df F value   Pr(>F)   
## group   2  6.3527 0.002259 **
##       147                    
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{leveneTest}\NormalTok{(}\AttributeTok{y =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{SepalWidthCm, }\AttributeTok{group =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{Species, }\AttributeTok{center =} \StringTok{"median"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Levene's Test for Homogeneity of Variance (center = "median")
##        Df F value Pr(>F)
## group   2  0.6475 0.5248
##       147
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{leveneTest}\NormalTok{(}\AttributeTok{y =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{PetalLengthCm, }\AttributeTok{group =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{Species, }\AttributeTok{center =} \StringTok{"median"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Levene's Test for Homogeneity of Variance (center = "median")
##        Df F value    Pr(>F)    
## group   2   19.72 2.589e-08 ***
##       147                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{leveneTest}\NormalTok{(}\AttributeTok{y =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{PetalWidthCm, }\AttributeTok{group =}\NormalTok{ data}\SpecialCharTok{$}\NormalTok{Species, }\AttributeTok{center =} \StringTok{"median"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Levene's Test for Homogeneity of Variance (center = "median")
##        Df F value    Pr(>F)    
## group   2  19.412 3.302e-08 ***
##       147                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

De acuerdo con el test aplicado se encuentran diferencias entre los tres
grupos de especies de iris en todos los atributos a excepción de la
característica ancho del sépalo, de lo cual ya se tenia cierto indicio
desde el punto de vista gráfico con los diagramas de caja desglasado por
especie, pues se indicaba que si bien se presentaban diferencias en las
medianas, estas no eran muy marcadas en comparación a los otros
atributos según especie de iris.

\hypertarget{aplicaciuxf3n-de-pruebas-estaduxedsticas-para-comparar-los-grupos-de-datos.-en-funciuxf3n-de-los-datos-y-el-objetivo-del-estudio-aplicar-pruebas-de-contraste-de-hipuxf3tesis-correlaciones-regresiones-etc.-aplicar-al-menos-tres-muxe9todos-de-anuxe1lisis-diferentes.}{%
\section{4.3. Aplicación de pruebas estadísticas para comparar los
grupos de datos. En función de los datos y el objetivo del estudio,
aplicar pruebas de contraste de hipótesis, correlaciones, regresiones,
etc. Aplicar al menos tres métodos de análisis
diferentes.}\label{aplicaciuxf3n-de-pruebas-estaduxedsticas-para-comparar-los-grupos-de-datos.-en-funciuxf3n-de-los-datos-y-el-objetivo-del-estudio-aplicar-pruebas-de-contraste-de-hipuxf3tesis-correlaciones-regresiones-etc.-aplicar-al-menos-tres-muxe9todos-de-anuxe1lisis-diferentes.}}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Anova}
\CommentTok{\# Longitud del sépalo}
\NormalTok{AnovaSL }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(SepalLengthCm }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Species, }\AttributeTok{data =}\NormalTok{ data)}
\FunctionTok{summary}\NormalTok{(AnovaSL)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Df Sum Sq Mean Sq F value Pr(>F)    
## Species       2  63.21  31.606   119.3 <2e-16 ***
## Residuals   147  38.96   0.265                   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Anova}
\CommentTok{\# Ancho del sépalo}
\NormalTok{AnovaSW }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(SepalWidthCm }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Species, }\AttributeTok{data =}\NormalTok{ data)}
\FunctionTok{summary}\NormalTok{(AnovaSW)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Df Sum Sq Mean Sq F value Pr(>F)    
## Species       2  10.98   5.489   47.36 <2e-16 ***
## Residuals   147  17.04   0.116                   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Anova}
\CommentTok{\# Longitud del pétalo}
\NormalTok{AnovaPL }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(PetalLengthCm }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Species, }\AttributeTok{data =}\NormalTok{ data)}
\FunctionTok{summary}\NormalTok{(AnovaPL)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Df Sum Sq Mean Sq F value Pr(>F)    
## Species       2  436.6  218.32    1179 <2e-16 ***
## Residuals   147   27.2    0.19                   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Anova}
\CommentTok{\# Ancho de pétalo}
\NormalTok{AnovaPW }\OtherTok{\textless{}{-}} \FunctionTok{aov}\NormalTok{(PetalWidthCm }\SpecialCharTok{\textasciitilde{}}\NormalTok{ Species, }\AttributeTok{data =}\NormalTok{ data)}
\FunctionTok{summary}\NormalTok{(AnovaPW)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##              Df Sum Sq Mean Sq F value Pr(>F)    
## Species       2  80.60   40.30   959.3 <2e-16 ***
## Residuals   147   6.18    0.04                   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
\end{verbatim}

Se realiza un Anova con el fin comparar las medias de cada uno de los
atributos entre los grupos o especies de flores iris. Al establecer el
valor alfa en 0.05 y al ver en la tabla que el valor de p es menor a
alfa, se rechaza la hipótesis nula de que las medias son iguales, y se
concluye que la media de la longitud y ancho del sépalo y pétalo es
distinta entre las tres especies en todos los casos.

Al verificar la correlación entre los atributos de longitud y ancho del
sépalo y pétalo se observa que entre la longitud del sépalo y la
longitud y ancho del pétalo guardan una correlación positiva superior al
80\%. Mientras que el ancho del sépalo guarda una correlación negativa
con estas mismas variables, pero mucho menor (entre el 35\% y 42\%).
Finalmente entre la longitud y ancho del pétalo su correlación es
positiva y es del 96\% (muy alta) y, entre la longitud y ancho del
sépalo su correlación es negativa y muy baja (10\%).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Correlación}
\CommentTok{\# entre todas sin especie}
\NormalTok{M }\OtherTok{\textless{}{-}} \FunctionTok{cor}\NormalTok{(data[,}\DecValTok{1}\SpecialCharTok{:}\DecValTok{4}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{corrplot}\NormalTok{(M, }\AttributeTok{method =} \StringTok{"ellipse"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck42-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{M}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##               SepalLengthCm SepalWidthCm PetalLengthCm PetalWidthCm
## SepalLengthCm     1.0000000   -0.1093692     0.8717542    0.8179536
## SepalWidthCm     -0.1093692    1.0000000    -0.4205161   -0.3565441
## PetalLengthCm     0.8717542   -0.4205161     1.0000000    0.9627571
## PetalWidthCm      0.8179536   -0.3565441     0.9627571    1.0000000
\end{verbatim}

A continuación se presentan las correlaciones y diagramas de dispersión
con línea de regresión, por parejas de atributos, pero desglosadas por
cada especie de iris.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# longitud del sépalo y ancho del pétalo}
\FunctionTok{lapply}\NormalTok{(}\FunctionTok{split}\NormalTok{(data, Species), }\ControlFlowTok{function}\NormalTok{(x)\{}\FunctionTok{cor}\NormalTok{(x[,}\DecValTok{1}\NormalTok{], x[,}\DecValTok{2}\NormalTok{])\})}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`Iris-setosa`
## [1] 0.7467804
## 
## $`Iris-versicolor`
## [1] 0.5259107
## 
## $`Iris-virginica`
## [1] 0.4572278
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{SepalLengthCm, }\AttributeTok{y=}\NormalTok{SepalWidthCm, }\AttributeTok{shape=}\NormalTok{Species, }\AttributeTok{color=}\NormalTok{Species))}\SpecialCharTok{+}
\FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
\FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method=}\NormalTok{lm, }\AttributeTok{se=}\NormalTok{F, }\AttributeTok{fullrange=}\NormalTok{F)}\SpecialCharTok{+}
\FunctionTok{scale\_color\_brewer}\NormalTok{(}\AttributeTok{palette=}\StringTok{"Dark2"}\NormalTok{)}\SpecialCharTok{+}
\FunctionTok{theme\_minimal}\NormalTok{()}\SpecialCharTok{+}
\FunctionTok{stat\_ellipse}\NormalTok{(}\AttributeTok{type =} \StringTok{"norm"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{Práctica_2_files/figure-latex/chunck44-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# longitud del sépalo y longitud del pétalo}
\FunctionTok{lapply}\NormalTok{(}\FunctionTok{split}\NormalTok{(data, Species), }\ControlFlowTok{function}\NormalTok{(x)\{}\FunctionTok{cor}\NormalTok{(x[,}\DecValTok{1}\NormalTok{], x[,}\DecValTok{3}\NormalTok{])\})}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`Iris-setosa`
## [1] 0.2638741
## 
## $`Iris-versicolor`
## [1] 0.754049
## 
## $`Iris-virginica`
## [1] 0.8642247
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{SepalLengthCm, }\AttributeTok{y=}\NormalTok{PetalLengthCm, }\AttributeTok{shape=}\NormalTok{Species, }\AttributeTok{color=}\NormalTok{Species))}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method=}\NormalTok{lm, }\AttributeTok{se=}\NormalTok{F, }\AttributeTok{fullrange=}\NormalTok{F)}\SpecialCharTok{+}
  \FunctionTok{scale\_color\_brewer}\NormalTok{(}\AttributeTok{palette=}\StringTok{"Dark2"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{stat\_ellipse}\NormalTok{(}\AttributeTok{type =} \StringTok{"norm"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{Práctica_2_files/figure-latex/chunck45-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# longitud del sépalo y ancho del pétalo }
\FunctionTok{lapply}\NormalTok{(}\FunctionTok{split}\NormalTok{(data, Species), }\ControlFlowTok{function}\NormalTok{(x)\{}\FunctionTok{cor}\NormalTok{(x[,}\DecValTok{1}\NormalTok{], x[,}\DecValTok{4}\NormalTok{])\})}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`Iris-setosa`
## [1] 0.2790916
## 
## $`Iris-versicolor`
## [1] 0.5464611
## 
## $`Iris-virginica`
## [1] 0.2811077
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{SepalLengthCm, }\AttributeTok{y=}\NormalTok{PetalWidthCm, }\AttributeTok{shape=}\NormalTok{Species, }\AttributeTok{color=}\NormalTok{Species))}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method=}\NormalTok{lm, }\AttributeTok{se=}\NormalTok{F, }\AttributeTok{fullrange=}\NormalTok{F)}\SpecialCharTok{+}
  \FunctionTok{scale\_color\_brewer}\NormalTok{(}\AttributeTok{palette=}\StringTok{"Dark2"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{stat\_ellipse}\NormalTok{(}\AttributeTok{type =} \StringTok{"norm"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{Práctica_2_files/figure-latex/chunck46-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ancho del sépalo y longitud del pétalo}
\FunctionTok{lapply}\NormalTok{(}\FunctionTok{split}\NormalTok{(data, Species), }\ControlFlowTok{function}\NormalTok{(x)\{}\FunctionTok{cor}\NormalTok{(x[,}\DecValTok{2}\NormalTok{], x[,}\DecValTok{3}\NormalTok{])\})}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`Iris-setosa`
## [1] 0.1766946
## 
## $`Iris-versicolor`
## [1] 0.5605221
## 
## $`Iris-virginica`
## [1] 0.4010446
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{SepalWidthCm, }\AttributeTok{y=}\NormalTok{PetalLengthCm, }\AttributeTok{shape=}\NormalTok{Species, }\AttributeTok{color=}\NormalTok{Species))}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method=}\NormalTok{lm, }\AttributeTok{se=}\NormalTok{F, }\AttributeTok{fullrange=}\NormalTok{F)}\SpecialCharTok{+}
  \FunctionTok{scale\_color\_brewer}\NormalTok{(}\AttributeTok{palette=}\StringTok{"Dark2"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{stat\_ellipse}\NormalTok{(}\AttributeTok{type =} \StringTok{"norm"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{Práctica_2_files/figure-latex/chunck47-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ancho del sépalo y ancho del pétalo}
\FunctionTok{lapply}\NormalTok{(}\FunctionTok{split}\NormalTok{(data, Species), }\ControlFlowTok{function}\NormalTok{(x)\{}\FunctionTok{cor}\NormalTok{(x[,}\DecValTok{2}\NormalTok{], x[,}\DecValTok{4}\NormalTok{])\})}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`Iris-setosa`
## [1] 0.2799729
## 
## $`Iris-versicolor`
## [1] 0.6639987
## 
## $`Iris-virginica`
## [1] 0.537728
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{SepalWidthCm, }\AttributeTok{y=}\NormalTok{PetalWidthCm, }\AttributeTok{shape=}\NormalTok{Species, }\AttributeTok{color=}\NormalTok{Species))}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method=}\NormalTok{lm, }\AttributeTok{se=}\NormalTok{F, }\AttributeTok{fullrange=}\NormalTok{F)}\SpecialCharTok{+}
  \FunctionTok{scale\_color\_brewer}\NormalTok{(}\AttributeTok{palette=}\StringTok{"Dark2"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{stat\_ellipse}\NormalTok{(}\AttributeTok{type =} \StringTok{"norm"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{Práctica_2_files/figure-latex/chunck48-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# longitud del pétalo y ancho de pétalo}
\FunctionTok{lapply}\NormalTok{(}\FunctionTok{split}\NormalTok{(data, Species), }\ControlFlowTok{function}\NormalTok{(x)\{}\FunctionTok{cor}\NormalTok{(x[,}\DecValTok{3}\NormalTok{], x[,}\DecValTok{4}\NormalTok{])\})}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $`Iris-setosa`
## [1] 0.3063082
## 
## $`Iris-versicolor`
## [1] 0.7866681
## 
## $`Iris-virginica`
## [1] 0.3221082
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{ggplot}\NormalTok{(data, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x=}\NormalTok{PetalLengthCm, }\AttributeTok{y=}\NormalTok{PetalWidthCm, }\AttributeTok{shape=}\NormalTok{Species, }\AttributeTok{color=}\NormalTok{Species))}\SpecialCharTok{+}
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method=}\NormalTok{lm, }\AttributeTok{se=}\NormalTok{F, }\AttributeTok{fullrange=}\NormalTok{F)}\SpecialCharTok{+}
  \FunctionTok{scale\_color\_brewer}\NormalTok{(}\AttributeTok{palette=}\StringTok{"Dark2"}\NormalTok{)}\SpecialCharTok{+}
  \FunctionTok{theme\_minimal}\NormalTok{()}\SpecialCharTok{+}
  \FunctionTok{stat\_ellipse}\NormalTok{(}\AttributeTok{type =} \StringTok{"norm"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## `geom_smooth()` using formula 'y ~ x'
\end{verbatim}

\includegraphics{Práctica_2_files/figure-latex/chunck49-1.pdf}

En cuanto a la correlación para cada uno de los grupos o especies de
flores iris se observa que en el caso de la especie setosa, los
atributos con correlaciones relevantes son la longitud y ancho del
sépalo (76\%). En cuanto a la especie versicolor, las correlaciones
superiores al 60\% ocurren entre las longitudes del sépalo y pétalo
(75\%) y entre los anchos del sépalo y pétalo (66\%). Y, en la especie
virginica, se presenta una única correlación alta entre las longitudes
del sépalo y pétalo (86\%).

Finalmente, el diagrama de dispersión -según las especies de flor iris-
visualizadas en conjunto permiten identificar la posible separación de
las especies. Se observa que las variables longitud y ancho del pétalo
son las dos variables con más potencial para poder separar entre
especies. Sin embargo, como se indicó en párrafos anteriores están
altamente correlacionadas, por lo que la información que aportan es en
gran medida redundante.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Diagrama de dispersión}
\FunctionTok{pairs}\NormalTok{(}\AttributeTok{x =}\NormalTok{ data[, }\SpecialCharTok{{-}}\DecValTok{5}\NormalTok{], }\AttributeTok{col =} \FunctionTok{c}\NormalTok{(}\StringTok{"firebrick"}\NormalTok{, }\StringTok{"green"}\NormalTok{, }\StringTok{"blue"}\NormalTok{)[data}\SpecialCharTok{$}\NormalTok{Species],}
      \AttributeTok{pch =} \DecValTok{20}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck50-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{par}\NormalTok{(}\AttributeTok{mfrow=}\FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{,}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

Ahora bien con el fin de clasificar las tres especies de iris a partir
de sus atributos de longitud y ancho del sépalo y pétalo se plantea
desarrollar un Análisis Discriminante Lineal o Linear Discrimiant
Analysis (LDA). La LDA es un método de clasificación de variables
cualitativas en el que dos o más grupos son conocidos a priori y nuevas
observaciones se clasifican en uno de ellos en función de sus
características. Haciendo uso del teorema de Bayes, LDA estima la
probabilidad de que una observación, dado un determinado valor de los
predictores, pertenezca a cada una de las clases de la variable
cualitativa, P(Y=k\textbar X=x). Finalmente se asigna la observación a
la clase k para la que la probabilidad predicha es mayor.

Se requieren las siguientes dos condiciones para que el LDA se considera
valido:

La primera es que cada predictor que forma parte del modelo se
distribuye de forma normal en cada una de las clases de la variable
respuesta. En un apartado anterior se presentaron los resultados y en
general se puede decir que la mayoría de los predictores en cada una de
las clases siguen la distribución normal, a excepción de la variable
ancho del pétalo, la cual no se distribuye de forma normal en las
especies setosa y versicolor.

En el caso de múltiples predictores, las observaciones siguen una
distribución normal multivariante en todas las clases.

Con el fin de verificar el cumplimiento de esta condición se aplica el
test de normalidad multivariante royston.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# LDA}
\CommentTok{\# Verificar normalidad multivariante}
\CommentTok{\# test de royston}
\NormalTok{royston\_test }\OtherTok{\textless{}{-}} \FunctionTok{mvn}\NormalTok{(}\AttributeTok{data =}\NormalTok{ data[,}\SpecialCharTok{{-}}\DecValTok{5}\NormalTok{], }\AttributeTok{mvnTest =} \StringTok{"royston"}\NormalTok{, }\AttributeTok{multivariatePlot =} \StringTok{"qq"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck52-1.pdf}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{royston\_test}\SpecialCharTok{$}\NormalTok{multivariateNormality}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      Test        H      p value MVN
## 1 Royston 50.64564 2.754697e-11  NO
\end{verbatim}

El test muestra evidencias significativas de falta de normalidad
multivariante. El LDA tiene cierta robustez frente a la falta de
normalidad multivariante, pero es importante tenerlo en cuenta en la
conclusión del análisis.

Y la segunda condición a cumplir es que la varianza del predictor es
igual en todas las clases de la variable respuesta. En el caso de
múltiples predictores, la matriz de covarianza es igual en todas las
clases. Si esto no se cumple se recurre a Análisis Discriminante
Cuadrático (QDA).

Con el fin de verificar el cumplimiento de esta condición se aplica el
test Box M, el cual se utiliza en el caso multivariante y permite
contrastar la igualdad de matrices entre grupos.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# ¿La matriz de covarianza es constante en todos los grupos?}
\FunctionTok{boxM}\NormalTok{(}\AttributeTok{data =}\NormalTok{ data[, }\SpecialCharTok{{-}}\DecValTok{5}\NormalTok{], }\AttributeTok{grouping =}\NormalTok{ data[, }\DecValTok{5}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Box's M-test for Homogeneity of Covariance Matrices
## 
## data:  data[, -5]
## Chi-Sq (approx.) = 139.24, df = 20, p-value < 2.2e-16
\end{verbatim}

El test Box's M muestra evidencias de que la matriz de covarianza no es
constante en todos los grupos, p(2.2e-16)\textless α(0.05), lo que a
priori descartaría el método LDA en favor del QDA. Sin embargo, como el
test Box's M es muy sensible a la falta de normalidad multivariante, con
frecuencia resulta significativo no porque la matriz de covarianza no
sea constante sino por la falta de normalidad, cosa que ocurre para los
datos en estudio. Por esta razón se va a asumir que la matriz de
covarianza sí es constante y que LDA puede alcanzar una buena precisión
en la clasificación. En la evaluación del modelo se verá como de buena
es esta aproximación.

Ahora bien, se procede al cálculo de la función discriminante:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Modelo LDA}
\NormalTok{modelo\_lda }\OtherTok{\textless{}{-}} \FunctionTok{lda}\NormalTok{(Species }\SpecialCharTok{\textasciitilde{}}\NormalTok{ SepalWidthCm }\SpecialCharTok{+}\NormalTok{ SepalLengthCm }\SpecialCharTok{+}\NormalTok{ PetalLengthCm }\SpecialCharTok{+}
\NormalTok{                    PetalWidthCm, }\AttributeTok{data =}\NormalTok{ data)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Modelo LDA}
\NormalTok{modelo\_lda}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## lda(Species ~ SepalWidthCm + SepalLengthCm + PetalLengthCm + 
##     PetalWidthCm, data = data)
## 
## Prior probabilities of groups:
##     Iris-setosa Iris-versicolor  Iris-virginica 
##       0.3333333       0.3333333       0.3333333 
## 
## Group means:
##                 SepalWidthCm SepalLengthCm PetalLengthCm PetalWidthCm
## Iris-setosa            3.418         5.006         1.464        0.244
## Iris-versicolor        2.770         5.936         4.260        1.326
## Iris-virginica         2.974         6.588         5.552        2.026
## 
## Coefficients of linear discriminants:
##                      LD1         LD2
## SepalWidthCm   1.5478732  2.15471106
## SepalLengthCm  0.8192685  0.03285975
## PetalLengthCm -2.1849406 -0.93024679
## PetalWidthCm  -2.8538500  2.80600460
## 
## Proportion of trace:
##    LD1    LD2 
## 0.9915 0.0085
\end{verbatim}

\hypertarget{representaciuxf3n-de-los-resultados-a-partir-de-tablas-y-gruxe1ficas.}{%
\section{5. Representación de los resultados a partir de tablas y
gráficas.}\label{representaciuxf3n-de-los-resultados-a-partir-de-tablas-y-gruxe1ficas.}}

Se procede a realizar la predicción con el mismo dataset (original)

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Realiza la predicciónn con el modelo LDA}
\NormalTok{prediccion}\OtherTok{\textless{}{-}}\FunctionTok{predict}\NormalTok{(modelo\_lda,data[}\SpecialCharTok{{-}}\DecValTok{5}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

Una vez que las normas de clasificación se han establecido, se tiene que
evaluar como de buena es la clasificación resultante. En otras palabras,
evaluar el porcentaje de aciertos en las clasificaciones. Para tal fin
se presenta la matriz de confusión, la cual presenta el número de
verdaderos positivos, verdaderos negativos, falsos positivos y falsos
negativos.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Matriz de confusión}
\NormalTok{m\_confusion}\OtherTok{\textless{}{-}}\FunctionTok{table}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Species,prediccion}\SpecialCharTok{$}\NormalTok{class,}
                   \AttributeTok{dnn=}\FunctionTok{c}\NormalTok{(}\StringTok{"Real"}\NormalTok{,}\StringTok{"Predicho"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Matriz de confusión}
\NormalTok{m\_confusion}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  Predicho
## Real              Iris-setosa Iris-versicolor Iris-virginica
##   Iris-setosa              50               0              0
##   Iris-versicolor           0              48              2
##   Iris-virginica            0               1             49
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Matriz de confusión}
\FunctionTok{mosaicplot}\NormalTok{(m\_confusion,}\AttributeTok{col=}\DecValTok{2}\SpecialCharTok{:}\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck60-1.pdf}

Solo 3 de las 150 predicciones que ha realizado el modelo han sido
erróneas.

Ahora bien, para evaluar el error de clasificación se emplean las mismas
observaciones con las que se ha creado el modelo, obteniendo así lo que
se denomina el training error. Si bien esta es una forma sencilla de
estimar la precisión en la clasificación, tiende a ser muy optimista. Es
más adecuado evaluar el modelo empleando observaciones nuevas que el
modelo no ha visto, obteniendo así el test error.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Presición (training error)}
\NormalTok{precision}\OtherTok{=}\FunctionTok{mean}\NormalTok{(data}\SpecialCharTok{$}\NormalTok{Species}\SpecialCharTok{==}\NormalTok{prediccion}\SpecialCharTok{$}\NormalTok{class)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Presición (training error)}
\NormalTok{precision}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.98
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Presición (training error)}
\NormalTok{error}\OtherTok{=}\NormalTok{ (}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{precision)}\SpecialCharTok{*}\DecValTok{100}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{error}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2
\end{verbatim}

El trainig error es muy bajo (2\%), lo que apunta a que el modelo es
bueno. Sin embargo, para validarlo es necesario un nuevo set de datos
con el que calcular el test error o recurrir a validación cruzada.

Se presenta a continuación una visualización que representa los límites
de clasificación de un modelo discriminante lineal para cada par de
predictores. Cada color representa una región de clasificación acorde al
modelo, se muestra el centroide de cada región y el valor real de las
observaciones.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Visualización de las clasificaciones}
\FunctionTok{partimat}\NormalTok{(Species }\SpecialCharTok{\textasciitilde{}}\NormalTok{ SepalWidthCm }\SpecialCharTok{+}\NormalTok{ SepalLengthCm }\SpecialCharTok{+}\NormalTok{ PetalLengthCm }\SpecialCharTok{+}\NormalTok{ PetalWidthCm,}
         \AttributeTok{data =}\NormalTok{ data, }\AttributeTok{method =} \StringTok{"lda"}\NormalTok{, }\AttributeTok{prec =} \DecValTok{200}\NormalTok{,}
         \AttributeTok{image.colors =} \FunctionTok{c}\NormalTok{(}\StringTok{"firebrick"}\NormalTok{, }\StringTok{"green"}\NormalTok{, }\StringTok{"blue"}\NormalTok{),}
         \AttributeTok{col.mean =} \StringTok{"firebrick"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck65-1.pdf}

Creación de un sets de entrenamiento y prueba

Se crea un set de entrenamiento para generar un modelo predictivo, y un
set de prueba, para comprobar la eficacia de este modelo para hacer
predicciones correctas.

Se obtiene un subconjunto del dataset original, que consiste en 70\% del
total de ellos. Y se obtiene el subconjunto de datos complementario al
de entrenamiento para el set de prueba, esto es, el 30\% restante.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Creación de un sets de entrenamiento y prueba}
\FunctionTok{set.seed}\NormalTok{(}\DecValTok{1234}\NormalTok{)}
\NormalTok{data\_entrenamiento }\OtherTok{\textless{}{-}} \FunctionTok{sample\_frac}\NormalTok{(data, .}\DecValTok{7}\NormalTok{)}
\NormalTok{data\_prueba }\OtherTok{\textless{}{-}} \FunctionTok{setdiff}\NormalTok{(data, data\_entrenamiento)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Verificación del set de entrenamiento y prueba}
\FunctionTok{str}\NormalTok{(data\_entrenamiento)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    105 obs. of  5 variables:
##  $ SepalLengthCm: num  5.2 5.7 6.3 6.5 6.3 6.4 6.8 7.9 6.2 7.1 ...
##  $ SepalWidthCm : num  3.5 2.6 3.3 3.2 3.4 2.8 3.2 3.8 2.9 3 ...
##  $ PetalLengthCm: num  1.5 3.5 6 5.1 5.6 5.6 5.9 6.4 4.3 5.9 ...
##  $ PetalWidthCm : num  0.2 1 2.5 2 2.4 2.2 2.3 2 1.3 2.1 ...
##  $ Species      : Factor w/ 3 levels "Iris-setosa",..: 1 2 3 3 3 3 3 3 2 3 ...
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{str}\NormalTok{(data\_prueba)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 'data.frame':    45 obs. of  5 variables:
##  $ SepalLengthCm: num  5.1 4.6 4.8 5.8 5.1 4.6 5.1 5.2 4.8 5.2 ...
##  $ SepalWidthCm : num  3.5 3.4 3.4 4 3.5 3.6 3.3 3.4 3.1 4.1 ...
##  $ PetalLengthCm: num  1.4 1.4 1.6 1.2 1.4 1 1.7 1.4 1.6 1.5 ...
##  $ PetalWidthCm : num  0.2 0.3 0.2 0.2 0.3 0.2 0.5 0.2 0.2 0.1 ...
##  $ Species      : Factor w/ 3 levels "Iris-setosa",..: 1 1 1 1 1 1 1 1 1 1 ...
\end{verbatim}

Se procede a calcular la función discriminante con el set de
entrenamiento:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# LDA con el set de entrenamiento}
\NormalTok{modelo\_lda }\OtherTok{\textless{}{-}} \FunctionTok{lda}\NormalTok{(Species }\SpecialCharTok{\textasciitilde{}}\NormalTok{ SepalWidthCm }\SpecialCharTok{+}\NormalTok{ SepalLengthCm }\SpecialCharTok{+}\NormalTok{ PetalLengthCm }\SpecialCharTok{+}
\NormalTok{                    PetalWidthCm, }\AttributeTok{data =}\NormalTok{ data\_entrenamiento)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{modelo\_lda}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Call:
## lda(Species ~ SepalWidthCm + SepalLengthCm + PetalLengthCm + 
##     PetalWidthCm, data = data_entrenamiento)
## 
## Prior probabilities of groups:
##     Iris-setosa Iris-versicolor  Iris-virginica 
##       0.3238095       0.3238095       0.3523810 
## 
## Group means:
##                 SepalWidthCm SepalLengthCm PetalLengthCm PetalWidthCm
## Iris-setosa         3.370588      4.991176      1.473529    0.2323529
## Iris-versicolor     2.767647      5.920588      4.255882    1.3500000
## Iris-virginica      3.024324      6.640541      5.654054    2.0351351
## 
## Coefficients of linear discriminants:
##                     LD1         LD2
## SepalWidthCm   1.252587 -2.69650836
## SepalLengthCm  1.059991  0.20893018
## PetalLengthCm -2.475107  0.08323739
## PetalWidthCm  -2.740318 -1.03024775
## 
## Proportion of trace:
##    LD1    LD2 
## 0.9931 0.0069
\end{verbatim}

Se realiza la predicción con el modelo LDA sobre el set de prueba:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Predicción con el set de prueba}
\NormalTok{prediccion}\OtherTok{\textless{}{-}}\FunctionTok{predict}\NormalTok{(modelo\_lda,data\_prueba[}\SpecialCharTok{{-}}\DecValTok{5}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

Se procede a evaluar la clasificación del modelo LDA:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Matriz de confusión}
\NormalTok{m\_confusion}\OtherTok{\textless{}{-}}\FunctionTok{table}\NormalTok{(data\_prueba}\SpecialCharTok{$}\NormalTok{Species,prediccion}\SpecialCharTok{$}\NormalTok{class,}
                   \AttributeTok{dnn=}\FunctionTok{c}\NormalTok{(}\StringTok{"Real"}\NormalTok{,}\StringTok{"Predicho"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{m\_confusion}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##                  Predicho
## Real              Iris-setosa Iris-versicolor Iris-virginica
##   Iris-setosa              16               0              0
##   Iris-versicolor           0              16              0
##   Iris-virginica            0               0             13
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{mosaicplot}\NormalTok{(m\_confusion,}\AttributeTok{col=}\DecValTok{2}\SpecialCharTok{:}\DecValTok{4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck73-1.pdf}

Se presenta la presición del modelo LDA:

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Presición (test error)}
\NormalTok{precision}\OtherTok{=}\FunctionTok{mean}\NormalTok{(data\_prueba}\SpecialCharTok{$}\NormalTok{Species}\SpecialCharTok{==}\NormalTok{prediccion}\SpecialCharTok{$}\NormalTok{class)}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{precision}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{error}\OtherTok{=}\NormalTok{(}\DecValTok{1}\SpecialCharTok{{-}}\NormalTok{precision)}\SpecialCharTok{*}\DecValTok{100}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{error}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0
\end{verbatim}

De acuerdo con el modelo ninguna de las 45 predicciones realizadas ha
sido incorrecta; el test de error es del 0\%.

Se presenta la visualización del resultado del modelo LDA:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{partimat}\NormalTok{(Species }\SpecialCharTok{\textasciitilde{}}\NormalTok{ SepalWidthCm }\SpecialCharTok{+}\NormalTok{ SepalLengthCm }\SpecialCharTok{+}\NormalTok{ PetalLengthCm }\SpecialCharTok{+}\NormalTok{ PetalWidthCm,}
         \AttributeTok{data =}\NormalTok{ data\_prueba, }\AttributeTok{method =} \StringTok{"lda"}\NormalTok{, }\AttributeTok{prec =} \DecValTok{200}\NormalTok{,}
         \AttributeTok{image.colors =} \FunctionTok{c}\NormalTok{(}\StringTok{"firebrick"}\NormalTok{, }\StringTok{"green"}\NormalTok{, }\StringTok{"blue"}\NormalTok{),}
         \AttributeTok{col.mean =} \StringTok{"firebrick"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\includegraphics{Práctica_2_files/figure-latex/chunck78-1.pdf}

\hypertarget{resoluciuxf3n-del-problema.-a-partir-de-los-resultados-obtenidos-cuuxe1les-son-las-conclusiones-los-resultados-permiten-responder-al-problema}{%
\section{6. Resolución del problema. A partir de los resultados
obtenidos, ¿cuáles son las conclusiones? ¿Los resultados permiten
responder al
problema?}\label{resoluciuxf3n-del-problema.-a-partir-de-los-resultados-obtenidos-cuuxe1les-son-las-conclusiones-los-resultados-permiten-responder-al-problema}}

El modelo de clasificación LDA desarrollado presentan muy buenos
resultados en la tarea de predecir o clasificar las especies de flores
iris a partir de los atributos de longitud y ancho del sépalo y pétalo,
tanto en los datos originales como con datos de prueba.

\end{document}
